version: '3.8'

services:
  postgres_db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: labaDatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

  backend:
    depends_on:
      postgres_db:
        condition: service_started
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PORT:$PORT
    environment:
      - DB_HOST=postgres_db
      - DB_USER=$POSTGRES_USER
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - DB_NAME=$POSTGRES_DATABASE
      - DB_PORT=$POSTGRES_PORT
  migration:
    build:
      context: .\backend
    command:
      [
        "./wait-for-it/wait-for-it.sh",
        "postgres_db:5432",
        "--",
        "yarn",
        "typeorm:migration:run",
      ]
    links:
      - postgres_db
    depends_on:
      - postgres_db
    env_file: ./.env
    environment:
      - DB_HOST=postgres_db

networks:
  postgres_network:
    driver: bridge

volumes:
  postgres_data:
