# Используем официальный образ PostgreSQL
FROM postgres:latest

# Настраиваем переменные окружения
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=labaDatabase

# Экспонируем стандартный порт PostgreSQL
EXPOSE 5432
